@extends('user.layout')
@section('title', 'My Queries - Shaadi Sense')
@section('content')
<div class="space-y-6 max-w-6xl">
    <div><h1 class="text-3xl font-extrabold text-slate-900 serif-title">Queries</h1><p class="text-sm text-slate-500 mt-1">Ask a question and view replies from the Shaadi Sense team.</p></div>
    <form id="query-form" action="{{ route('user.queries.store') }}" method="POST" class="scroll-mt-8 bg-white border border-slate-200 rounded-3xl p-6 grid sm:grid-cols-2 gap-4">@csrf
        @if(session('success'))<div class="sm:col-span-2 rounded-xl bg-emerald-50 border border-emerald-100 p-3 text-xs font-bold text-emerald-700">{{ session('success') }}</div>@endif
        <input name="phone" value="{{ old('phone', auth()->user()->mobile_number) }}" placeholder="Phone number" class="rounded-xl border border-slate-200 px-4 py-3 text-sm"><input name="subject" value="{{ old('subject') }}" required placeholder="Subject" class="rounded-xl border border-slate-200 px-4 py-3 text-sm"><textarea name="message" required rows="4" placeholder="How can we help?" class="sm:col-span-2 rounded-xl border border-slate-200 px-4 py-3 text-sm">{{ old('message') }}</textarea><button class="sm:col-span-2 bg-[#850625] text-white rounded-xl px-6 py-3 text-sm font-bold">Submit Query</button>
    </form>
    <div class="rounded-3xl bg-white border border-slate-200 overflow-hidden"><div class="overflow-x-auto"><table class="min-w-full text-sm">
        <thead class="bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-4">Subject</th><th class="px-5 py-4">My Query</th><th class="px-5 py-4">Admin Reply</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Created</th><th class="px-5 py-4 text-right">Actions</th></tr></thead>
        <tbody class="divide-y divide-slate-100">@forelse($queries as $query)<tr class="align-top hover:bg-slate-50/60"><td class="px-5 py-4 font-bold text-slate-800">{{ $query->subject }}</td><td class="px-5 py-4 max-w-xs text-slate-600">{{ $query->message }}</td><td class="px-5 py-4 max-w-xs">@if($query->admin_reply)<div class="rounded-xl bg-emerald-50 p-3 text-emerald-800">{{ $query->admin_reply }}</div>@else<span class="text-slate-400">Awaiting reply</span>@endif</td><td class="px-5 py-4"><span class="text-[10px] font-extrabold uppercase text-[#850625]">{{ $query->status }}</span></td><td class="px-5 py-4 whitespace-nowrap text-xs text-slate-500">{{ $query->created_at->format('d M Y') }}<br>{{ $query->created_at->format('h:i A') }}</td><td class="px-5 py-4"><div class="flex justify-end gap-2">@unless($query->replied_at)<details><summary class="cursor-pointer list-none rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold">Edit</summary><form action="{{ route('user.queries.update', $query) }}" method="POST" class="mt-2 w-80 space-y-2 rounded-xl border bg-white p-4 shadow">@csrf @method('PUT')<input name="phone" value="{{ $query->phone }}" class="w-full border rounded-lg p-2"><input name="subject" value="{{ $query->subject }}" class="w-full border rounded-lg p-2" required><textarea name="message" rows="4" class="w-full border rounded-lg p-2" required>{{ $query->message }}</textarea><button class="w-full rounded-lg bg-[#850625] py-2 text-xs font-bold text-white">Save</button></form></details>@endunless<form action="{{ route('user.queries.destroy', $query) }}" method="POST" onsubmit="return confirm('Delete this query?')">@csrf @method('DELETE')<button class="rounded-lg bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700">Delete</button></form></div></td></tr>@empty<tr><td colspan="6" class="p-12 text-center text-slate-400">You have not submitted any queries.</td></tr>@endforelse</tbody>
    </table></div><div class="border-t p-4">{{ $queries->links() }}</div></div>
</div>
@endsection
