@extends('admin.layout')

@section('content')
<div class="space-y-6 mt-6 relative z-30">
    <div class="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><a href="{{ route('admin.users.index') }}" class="text-xs font-bold text-[#3950a2]">← Back to users</a><h1 class="mt-2 text-3xl font-extrabold text-slate-800">{{ $user->name }} - Generated Plans</h1><p class="mt-1 text-sm text-slate-500">Review requirements, detailed costs and AI audit data.</p></div><div class="rounded-xl bg-slate-100 px-4 py-3 text-xs"><strong>{{ $user->email }}</strong><br>{{ $plans->total() }} plans</div></div>
    <div class="rounded-xl border border-slate-200 bg-white shadow-sm overflow-hidden"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-100 text-sm"><thead class="bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-6 py-4">Plan</th><th class="px-6 py-4">Guests</th><th class="px-6 py-4">Cost</th><th class="px-6 py-4">Model / Status</th><th class="px-6 py-4">Generated</th><th class="px-6 py-4 text-right">Action</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($plans as $plan)<tr class="hover:bg-slate-50"><td class="px-6 py-4"><div class="font-bold text-slate-800">{{ $plan->title }}</div><div class="mt-1 text-xs text-slate-400">{{ $plan->suggestions_count }} alternatives</div></td><td class="px-6 py-4 font-semibold">{{ number_format($plan->guest_count) }}</td><td class="px-6 py-4 font-bold text-[#850625]">₹{{ number_format((float) $plan->total_cost) }}</td><td class="px-6 py-4"><div class="text-xs font-semibold">{{ $plan->model ?: 'Not recorded' }}</div><span class="mt-1 inline-flex rounded bg-emerald-50 px-2 py-0.5 text-[10px] font-bold uppercase text-emerald-700">{{ $plan->status }}</span></td><td class="px-6 py-4 text-xs text-slate-500">{{ $plan->created_at->format('d M Y, h:i A') }}</td><td class="px-6 py-4 text-right"><a href="{{ route('admin.users.plans.show', $plan) }}" class="inline-flex items-center rounded-lg bg-[#3950a2] px-4 py-2 text-xs font-bold text-white">View complete plan</a></td></tr>@empty<tr><td colspan="6" class="px-6 py-12 text-center text-slate-400">This user has not generated any plans.</td></tr>@endforelse</tbody></table></div></div>
    {{ $plans->links() }}
</div>
@endsection
