@extends('admin.layout')

@section('content')
<div class="space-y-6 mt-6 relative z-30">
    <div class="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><a href="{{ route('admin.users.plans.index', $plan->user) }}" class="text-xs font-bold text-[#3950a2]">← {{ $plan->user->name }}'s plans</a><h1 class="mt-2 text-3xl font-extrabold text-slate-800">{{ $presentation['title'] }}</h1><p class="mt-1 text-sm text-slate-500">Complete requirement, costing, vendor and AI audit record.</p></div><a href="{{ route('admin.users.plans.download', $plan) }}" class="inline-flex items-center gap-2 rounded-xl bg-[#850625] px-5 py-3 text-xs font-bold text-white"><svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2"><path stroke-linecap="round" stroke-linejoin="round" d="M12 3v12m0 0 4-4m-4 4-4-4M5 21h14"/></svg>Download PDF</a></div>

    <section class="grid grid-cols-1 md:grid-cols-4 gap-4">@foreach([['User', $plan->user->name], ['Guests', number_format($plan->guest_count)], ['Total Cost', '₹'.number_format((float) $plan->total_cost)], ['Generated', $plan->created_at->format('d M Y, h:i A')]] as [$label,$value])<div class="rounded-xl border border-slate-200 bg-white p-5"><div class="text-[10px] font-bold uppercase tracking-wider text-slate-400">{{ $label }}</div><div class="mt-2 font-extrabold text-slate-800">{{ $value }}</div></div>@endforeach</section>

    <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-extrabold text-slate-800">User Requirements</h2><div class="mt-4 grid grid-cols-1 md:grid-cols-2 gap-3">@foreach($presentation['answers'] as $key => $value)<div class="rounded-lg bg-slate-50 p-4"><div class="text-[10px] font-bold uppercase tracking-wider text-slate-400">{{ str($key)->replace('_',' ')->title() }}</div><div class="mt-1 text-sm font-semibold text-slate-700">{{ is_array($value) ? implode(', ', $value) : $value }}</div></div>@endforeach</div></section>

    <section class="space-y-4"><h2 class="text-xl font-extrabold text-slate-800">Detailed Costing</h2>@foreach($presentation['costing'] as $item)<article class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex justify-between gap-4"><div><h3 class="text-lg font-extrabold text-slate-800">{{ $item['category'] }}</h3><p class="mt-1 text-xs text-slate-500">{{ $item['summary'] ?? '' }}</p></div><div class="text-xl font-extrabold text-[#850625]">₹{{ number_format((float) $item['amount']) }}</div></div><div class="mt-4 grid grid-cols-1 md:grid-cols-3 gap-3">@foreach($item['attributes'] as $attribute)<div class="rounded-lg bg-slate-50 p-4"><div class="text-xs font-bold text-slate-700">{{ $attribute['name'] }}</div><div class="mt-1 text-[10px] text-slate-400">{{ $attribute['value'] }}</div><div class="mt-2 font-bold text-[#850625]">₹{{ number_format((float) $attribute['cost']) }}</div></div>@endforeach</div></article>@endforeach</section>

    <section class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><h2 class="text-xl font-extrabold text-slate-800">Matched Vendor Names and Attributes</h2><div class="mt-4 grid grid-cols-1 xl:grid-cols-2 gap-4">@forelse($presentation['recommendations'] as $vendor)<article class="rounded-xl border border-slate-200 overflow-hidden"><div class="bg-[#850625] px-5 py-3 text-white"><div class="text-[9px] uppercase tracking-wider text-rose-200">{{ $vendor['category'] }}</div><div class="font-bold">{{ $vendor['name'] }}</div></div><div class="p-4"><p class="text-xs text-slate-500">{{ $vendor['reason'] }}</p><div class="mt-3 space-y-2">@foreach($vendor['attributes'] as $attribute)<div class="flex justify-between gap-3 rounded bg-slate-50 p-2 text-xs"><span><strong>{{ $attribute['name'] }}</strong><br><small class="text-slate-400">{{ $attribute['value'] }}</small></span><strong class="text-[#850625]">₹{{ number_format((float) $attribute['cost']) }}</strong></div>@endforeach</div></div></article>@empty<div class="text-sm text-slate-400">No vendor was explicitly shortlisted.</div>@endforelse</div></section>

    <section class="rounded-xl border border-amber-200 bg-amber-50 p-6"><div class="flex flex-wrap justify-between gap-4"><div><h2 class="text-xl font-extrabold text-slate-800">AI Audit Details</h2><p class="mt-1 text-xs text-slate-500">Exact prompt stored when this plan was generated.</p></div><div class="text-right text-xs"><strong>Model:</strong> {{ $plan->model ?: 'Not recorded' }}<br><strong>Status:</strong> {{ $plan->status }}</div></div><pre class="mt-4 max-h-[500px] overflow-auto whitespace-pre-wrap break-words rounded-xl bg-slate-900 p-5 text-xs leading-relaxed text-slate-100">{{ $plan->requirement_prompt }}</pre></section>
</div>
@endsection
