@extends('admin.layout')
@section('content')
<div class="space-y-6 mt-6 relative z-30">
    <div><h1 class="text-3xl font-extrabold text-slate-800">User Queries</h1><p class="text-sm text-slate-500 mt-1">View user details, manage queries, and send replies by email.</p>@include('admin.partials.alerts')</div>
    <form class="bg-white border rounded-xl p-4 flex flex-wrap gap-3"><input name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Name, email or subject" class="border rounded-lg px-3 py-2 text-sm flex-1 min-w-64"><select name="status" class="border rounded-lg px-3 py-2 text-sm"><option value="">All statuses</option>@foreach(['open','replied','closed'] as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="bg-[#3950a2] text-white rounded-lg px-5 text-sm font-bold">Filter</button></form>
    <div class="rounded-xl bg-white shadow-sm border border-slate-200 overflow-hidden"><div class="overflow-x-auto">
        <table class="min-w-full text-sm text-slate-700">
            <thead class="bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-4">ID</th><th class="px-5 py-4">User Details</th><th class="px-5 py-4">Subject & Query</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Created</th><th class="px-5 py-4 text-right">Actions</th></tr></thead>
            <tbody class="divide-y divide-slate-100">@forelse($queries as $query)<tr class="align-top hover:bg-slate-50/60">
                <td class="px-5 py-4 font-bold text-slate-400">#{{ $query->id }}</td>
                <td class="px-5 py-4"><div class="font-bold text-slate-800">{{ $query->name }}</div><div class="text-xs text-slate-400">{{ $query->email }}</div><div class="text-xs text-slate-400">{{ $query->phone ?: 'No phone' }} · {{ $query->user ? 'User #'.$query->user_id : 'Guest' }}</div></td>
                <td class="px-5 py-4 max-w-md"><div class="font-bold text-slate-800">{{ $query->subject }}</div><div class="mt-1 text-xs text-slate-500 line-clamp-2">{{ $query->message }}</div>@if($query->admin_reply)<div class="mt-2 rounded-lg bg-emerald-50 p-2 text-xs text-emerald-800"><strong>Reply:</strong> {{ $query->admin_reply }}</div>@endif</td>
                <td class="px-5 py-4"><span class="inline-flex rounded-full px-3 py-1 text-[10px] font-extrabold uppercase {{ $query->status === 'replied' ? 'bg-emerald-50 text-emerald-700' : ($query->status === 'closed' ? 'bg-slate-100 text-slate-600' : 'bg-amber-50 text-amber-700') }}">{{ $query->status }}</span></td>
                <td class="px-5 py-4 text-xs whitespace-nowrap">{{ $query->created_at->format('d M Y') }}<br><span class="text-slate-400">{{ $query->created_at->format('h:i A') }}</span></td>
                <td class="px-5 py-4"><div class="flex justify-end gap-3">
                    <details><summary class="cursor-pointer list-none rounded-lg bg-indigo-50 px-3 py-2 text-xs font-bold text-indigo-700">Reply</summary><form action="{{ route('admin.user-queries.reply', $query) }}" method="POST" class="mt-2 w-80 rounded-xl border bg-white p-4 shadow">@csrf<textarea name="admin_reply" required rows="5" class="w-full border rounded-lg p-3 text-sm" placeholder="Reply emailed to user">{{ $query->admin_reply }}</textarea><button class="mt-2 w-full bg-emerald-600 text-white rounded-lg px-4 py-2 font-bold text-xs">Send Reply</button></form></details>
                    <details><summary class="cursor-pointer list-none rounded-lg bg-slate-100 px-3 py-2 text-xs font-bold text-slate-700">Edit</summary><form action="{{ route('admin.user-queries.update', $query) }}" method="POST" class="mt-2 grid w-96 grid-cols-2 gap-2 rounded-xl border bg-white p-4 shadow">@csrf @method('PUT')<input name="name" value="{{ $query->name }}" class="border rounded-lg p-2" required><input name="email" type="email" value="{{ $query->email }}" class="border rounded-lg p-2" required><input name="phone" value="{{ $query->phone }}" class="border rounded-lg p-2"><select name="status" class="border rounded-lg p-2">@foreach(['open','replied','closed'] as $status)<option value="{{ $status }}" @selected($query->status===$status)>{{ ucfirst($status) }}</option>@endforeach</select><input name="subject" value="{{ $query->subject }}" class="col-span-2 border rounded-lg p-2" required><textarea name="message" rows="4" class="col-span-2 border rounded-lg p-2" required>{{ $query->message }}</textarea><button class="col-span-2 bg-[#3950a2] text-white rounded-lg py-2 text-xs font-bold">Save Changes</button></form></details>
                    <form action="{{ route('admin.user-queries.destroy', $query) }}" method="POST" onsubmit="return confirm('Delete this query?')">@csrf @method('DELETE')<button class="rounded-lg bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700">Delete</button></form>
                </div></td>
            </tr>@empty<tr><td colspan="6" class="p-12 text-center text-slate-400">No user queries found.</td></tr>@endforelse</tbody>
        </table>
    </div><div class="border-t p-4">{{ $queries->links() }}</div></div>
</div>
@endsection
